tools:
  - name: configcat_cli
    image: configcat/cli
    description: Run ConfigCat CLI commands. receives the command to run as an argument
    alias: configcat
    content: |
      configcat {{.command}}
    args:
      command:
        description: 'The ConfigCat CLI command to run (example: settings list --config-id=<your_config_id>)'
        required: true
    env:
      - "CONFIGCAT_API_USER"
      - "CONFIGCAT_API_PASS"
      - "CONFIGCAT_TOKEN" # Fetched from Kubiya secret
      - "CONFIGCAT_PRODUCT_ID" # Product ID for ConfigCat
      - "CONFIGCAT_ORG_ID" # Organization ID for ConfigCat
      - "CONFIGCAT_CONFIG_ID" # Configuration ID for ConfigCat
    metadata:
      category: 
        - "ConfigCat"
      tags: 
        - "ConfigCat"
        - "CLI"
      image_url: "https://configcat.com/images/shared/configcat-logo-cat-canvas-800.png"
      documentation: "https://raw.githubusercontent.com/kubiyabot/community-tools/main/configcat/README.md"
