name: Deploy changed YAML - DEV

on:
  push:
    branches-ignore:
      - main
      - production
      - release-*
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  changed-files:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.set-matrix.outputs.files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we get the full history

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44.5.5
        with:
          json: true
          dir_names: false
          files: |
            **/*.yaml
            **/*.yml
          files_ignore: |
            {.github,.git}/**
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Set output files
        id: set-matrix
        run: echo "files=${{ steps.changed-files.outputs.all_modified_files }}" >> $GITHUB_OUTPUT

  process-files:
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix:
        file: ${{ fromJSON(needs.changed-files.outputs.files) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert YAML to JSON
        id: convert-yaml
        uses: fabasoad/data-format-converter-action@v0.2.3
        with:
          input: "${{ matrix.file }}"
          from: "yaml"
          to: "json"

      - name: Set JSON file environment variable
        run: |
          JSON_FILE=$(echo "${{ matrix.file }}" | sed 's/\.yaml$/.json/' | sed 's/\.yml$/.json/')
          echo "JSON_FILE=$JSON_FILE" >> $GITHUB_ENV

      - name: Validate JSON
        run: |
          echo "Validating $JSON_FILE file"
          echo '${{ steps.convert-yaml.outputs.output }}' >> $JSON_FILE
          jq . $JSON_FILE
        continue-on-error: true

      - name: Save JSON content to temporary file
        run: |
          JSON_FILE=$(echo "${{ matrix.file }}" | sed 's/\.yaml$/.json/' | sed 's/\.yml$/.json/')
          echo "{\"${{ matrix.file }}\": $(cat $JSON_FILE)}" > ${{ matrix.file }}.json
          cat ${{ matrix.file }}.json

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: json-files
          path: ${{ matrix.file }}.json

  summarize:
    runs-on: ubuntu-latest
    needs: [process-files]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: json-files
          path: ./json-files

      - name: Set up AWS CLI
        run: pip install awscli

      - name: Download existing combined.json from S3
        run: |
          aws s3 cp s3://kubiya-marketplace-prod/combined.json combined.json --region eu-west-1 || echo '{}' > combined.json
          cat combined.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_COMMUNITY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_COMMUNITY }}

      - name: Merge all JSON files into combined.json
        run: |
          jq -s 'reduce .[] as $item ({}; . * $item)' combined.json json-files/*.json > updated_combined.json
          cat updated_combined.json
          mv updated_combined.json combined.json

      - name: Upload updated combined.json to S3
        run: |
          echo "Uploading updated combined.json to S3"
          aws s3 cp combined.json s3://kubiya-marketplace-prod/combined.json --region eu-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_COMMUNITY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_COMMUNITY }}
        