name: Deploy changed YAML - DEV

on:
  push:
    branches-ignore:
      - main
      - production
      - release-*
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  process-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we get the full history

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44.5.5
        with:
          json: true
          dir_names: false
          files: |
            **/*.yaml
            **/*.yml
          files_ignore: |
            {.github,.git}/**

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Process each changed file
        run: |
          changed_files=$(echo '${{ steps.changed-files.outputs.all_changed_files }}' | jq -r '.[]')
          for file in $changed_files; do
            echo "Processing $file"
            JSON_FILE=$(echo "$file" | sed 's/\.yaml$/.json/' | sed 's/\.yml$/.json/')

            # Convert YAML to JSON
            yq eval -o=json $file > $JSON_FILE

            # Save JSON content to temporary file
            echo "{\"$file\": $(cat $JSON_FILE)}" > new_data.json
            cat new_data.json

            # Download existing combined.json from S3
            aws s3 cp s3://kubiya-marketplace-prod/combined.json combined.json --region eu-west-1 || echo '{}' > combined.json
            cat combined.json

            # Merge new data with existing combined.json
            jq -s '.[0] * .[1]' combined.json new_data.json > updated_combined.json
            cat updated_combined.json

            # Upload updated combined.json to S3
            echo "Uploading updated_combined.json to S3"
            aws s3 cp updated_combined.json s3://kubiya-marketplace-prod/combined.json --region eu-west-1

            echo "Completed processing $file"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
